homebrew_taps:
  
homebrew_casks:
  - flux
  - figma
  - font-cozette 
  - google-chrome 
  - iterm2 
  - libreoffice 
  - macs-fan-control 
  - monitorcontrol 
  - raycast
  - spotify 
  - visual-studio-code