---
- hosts: localhost
  vars_files:
    - .env.yml
  tasks:
    # Setup
    - ansible.builtin.include_tasks: 
        file: tasks/dotfiles.yml
      tags:
        - dotfiles
    # Packages
    - ansible.builtin.include_tasks: 
        file: tasks/zsh.yml
      tags: setup
    - ansible.builtin.include_tasks: 
        file: tasks/git.yml
      tags: git
    - ansible.builtin.include_tasks: 
        file: tasks/borgbackup.yml
      tags: setup
    - ansible.builtin.include_role: 
        name: elliotweiser.osx-command-line-tools
      tags: setup
    - ansible.builtin.include_tasks: 
        file: tasks/nvm.yml
      tags: nvm
    - ansible.builtin.include_tasks: 
        file: tasks/tmux.yml
      tags: setup
    - ansible.builtin.include_tasks: 
        file: tasks/vim.yml
      tags: setup
    # Apps
    - ansible.builtin.include_tasks: 
        file: tasks/mas.yml
    - ansible.builtin.include_tasks: 
        file: tasks/chrome.yml
    - ansible.builtin.include_tasks: 
        file: tasks/figma.yml
    - ansible.builtin.include_tasks: 
        file: tasks/firefox.yml
    - ansible.builtin.include_tasks: 
        file: tasks/flux.yml
    - ansible.builtin.include_tasks: 
        file: tasks/magnet.yml
    - ansible.builtin.include_tasks: 
        file: tasks/protonvpn.yml
    - ansible.builtin.include_tasks: 
        file: tasks/wireguard.yml
    - ansible.builtin.include_tasks: 
        file: tasks/iterm2.yml
    - ansible.builtin.include_tasks: 
        file: tasks/libreoffice.yml
    - ansible.builtin.include_tasks: 
        file: tasks/macs-fan-control.yml
    - ansible.builtin.include_tasks: 
        file: tasks/monitorcontrol.yml
    - ansible.builtin.include_tasks: 
        file: tasks/raycast.yml
    - ansible.builtin.include_tasks: 
        file: tasks/spotify.yml
    - ansible.builtin.include_tasks: 
        file: tasks/visual-studio-code.yml
    # Wrap up
    - ansible.builtin.include_tasks: 
        file: tasks/upgrade.yml