- name: Provision personal macOS device
  hosts: localhost # Run on the macOS device to be set up
  module_defaults:
    community.general.homebrew_cask:
      accept_external_apps: true
  roles:
    # setup
    - git
    - dotfiles
    # - zsh
    - elliotweiser.osx-command-line-tools
    - asdf
    # packages
    - nodejs
    - python
    - tmux
    - tree
    - vim
    - mas
    - upgrade
    # apps
    - chrome
    - figma
    - flux
    - magnet
    - iterm2
    - macs-fan-control
    - monitorcontrol
    - protonvpn
    - raycast
    - spotify
    - visual-studio-code
    - wireguard
