- name: Provision work macOS device
  hosts: localhost # Run on the macOS device to be setup
  module_defaults:
    community.general.homebrew_cask:
      accept_external_apps: true
  roles:
    # setup
    - basics
    - elliotweiser.osx-command-line-tools
    # packages
    - nodejs
    - upgrade
    # apps
    - mas
    - chrome
    - figma
    - flux
    - magnet
    - wireguard
    - iterm2
    - macs-fan-control
    - monitorcontrol
    - raycast
    - spotify
    - visual-studio-code
    # wrap up
    - role: macos
      vars:
        work: true
