---
- name: Provision my work macOS device
  hosts: localhost # Run on the macOS device to be setup
  module_defaults:
    community.general.homebrew_cask:
      accept_external_apps: true
  roles:
    - townk.beautiful_output
    - dotfiles
    - zsh
    - git
    - elliotweiser.osx-command-line-tools
    - nodejs
    - tmux
    - vim
    - mas
    - chrome
    - figma
    - flux
    - magnet
    - wireguard
    - iterm2
    - macs-fan-control
    - monitorcontrol
    - raycast
    - spotify
    - visual-studio-code
    - upgrade
