---
- name: Raspberry Pi
  hosts: pi
  tasks:
    - ansible.builtin.include_tasks: 
        file: tasks/sshd.yml
    - name: "Package: zsh"
      ansible.builtin.include_tasks:
        file: tasks/zsh.yml
    - name: "Set up dotfiles"
      ansible.builtin.include_tasks:
        file: tasks/dotfiles.yml
    - name: "Package: git"
      ansible.builtin.include_tasks:
        file: tasks/git.yml
    - name: "Package: tmux"
      ansible.builtin.include_tasks:
        file: tasks/tmux.yml
    - name: "Package: vim"
      ansible.builtin.include_tasks:
        file: tasks/vim.yml
    - ansible.builtin.include_tasks: 
      file: tasks/upgrade.yml