- hosts: vpn
  tasks:
    - ansible.builtin.include_tasks: 
        file: tasks/dotfiles.yml
    - ansible.builtin.include_tasks: 
        file: tasks/git.yml
    - ansible.builtin.include_tasks: 
        file: tasks/tmux.yml
    - ansible.builtin.include_tasks: 
        file: tasks/vim.yml
    - ansible.builtin.include_tasks: 
        file: tasks/zsh.yml
    - ansible.builtin.include_tasks: 
        file: tasks/sshd.yml
    - ansible.builtin.include_tasks: 
        file: tasks/upgrade.yml