- name: Install Git
  ansible.builtin.apt:
    name: git
  become: true
  when: ansible_facts['os_family'] == "Debian"
- name: Install Git
  community.general.homebrew:
    name: git
  when: ansible_distribution == 'MacOSX'
