- name: Install tree
  ansible.builtin.apt:
    name: tree
  become: true
  when: ansible_distribution == "Ubuntu"
- community.general.homebrew:
    name: tree
  when: ansible_distribution == 'MacOSX'
