---
- name: Borg
  ansible.builtin.apt:
    name:
      - borgbackup
  become: true
  when: ansible_facts['os_family'] == "Debian"
- name: Borg
  community.general.homebrew:
    name: borgbackup
  when: ansible_distribution == 'MacOSX'
