---
- ansible.builtin.apt:
    name:
      - borgbackup
  become: true
  when: ansible_facts['os_family'] == "Debian"
- community.general.homebrew:
    name: borgbackup
  when: ansible_distribution == 'MacOSX'