---
- ansible.builtin.apt:
    name:
      - borgbackup
  become: true
  when: ansible_distribution == "Ubuntu"
- community.general.homebrew:
    name: borgbackup
  when: ansible_distribution == 'MacOSX'