- community.general.homebrew:
    name: docker
  when: ansible_distribution == 'MacOSX'
- name: docker
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Ensure old versions of Docker are not installed.
      package:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
    - name: Ensure dependencies are installed.
      become: true
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
    - file:
        path: /etc/apt/keyrings
        state: directory
      become: true
    - stat:
        path: /etc/apt/keyrings/docker.gpg
      register: gpgkey
    - name: Add GPG key
      when: not gpgkey.stat.exists
      become: true
      block:
        - name: Add Docker’s official GPG key
          when: ansible_distribution == "Ubuntu"
          shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        - name: Add Docker’s official GPG key
          shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          when: ansible_distribution == "Debian"
    - stat:
        path: /etc/apt/sources.list.d/docker.list
      register: repository
    - name: Set up the repository
      become: true
      when: not repository.stat.exists
      block:
        - shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
          when: ansible_distribution == "Ubuntu"
        - shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
          when: ansible_distribution == "Debian"
    - name: Ensure dependencies are installed.
      become: true
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true
