- name: Ensure .dotfiles repo is present
  ansible.builtin.git:
    repo: https://github.com/macguirerintoul/.dotfiles.git
    dest: ~/.dotfiles
- ansible.builtin.file:
    path: "~/.dotfiles/home/.DS_Store"
    state: absent
- ansible.builtin.file:
    path: ~/.ssh
    state: directory
- name: Find all files in ~/.dotfiles/home
  find:
    paths: ~/.dotfiles/home
    hidden: true
    recurse: true
  register: find
- name: Create links to ~/.dotfiles/home from ~
  ansible.builtin.file:
    src: "{{ item.path }}"
    path: "~/{{ item.path | regex_search('(?<=.dotfiles\/home\/).*') }}"
    state: link
    force: true # force link if file already exists
  with_items: "{{ find.files | select('match', '^((?!.zsh_plugins).)*$')}}"
- ansible.builtin.file:
    src: ~/.dotfiles/home/.zsh_plugins
    path: ~/.zsh_plugins
    state: link