- name: Ensure .dotfiles repo is present
  ansible.builtin.git:
    # Use HTTPS to avoid having to set up an SSH key at GitHub
    repo: https://github.com/macguirerintoul/.dotfiles.git
    dest: ~/.dotfiles
- name: Ensure the ~/.ssh directory exists, so ~/.ssh/config can be copied
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
- name: Find all files in ~/.dotfiles/home
  find:
    paths: ~/.dotfiles/home
    hidden: true
    recurse: true
  register: find
- name: Create links to ~/.dotfiles/home from ~
  ansible.builtin.file:
    src: "{{ item.path }}"
    path: "~/{{ item.path | regex_search('(?<=.dotfiles\/home\/).*') }}"
    state: link
    force: true # force link if file already exists
  with_items: "{{ find.files | select('match', '^((?!.zsh_plugins|.vim).)*$')}}"
- name: Create link to Zsh plugins directory
  ansible.builtin.file:
    src: ~/.dotfiles/home/.zsh_plugins
    path: ~/.zsh_plugins
    state: link
    force: true # force link if file already exists
- name: Create link to Vim configuration directory
  ansible.builtin.file:
    src: ~/.dotfiles/home/.vim
    path: ~/.vim
    state: link
    force: true # force link if file already exists
