- name: Ensure git is installed
  block:
    - ansible.builtin.apt:
        name: git
      become: true
      when: ansible_facts['os_family'] == "Debian"
    - community.general.homebrew:
        name: git
      when: ansible_distribution == 'MacOSX'