---
- name: Install tmux
  ansible.builtin.apt:
    name: tmux
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install tmux
  community.general.homebrew:
    name: tmux
  when: ansible_distribution == 'MacOSX'
