---
- ansible.builtin.apt:
    name: tmux
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"
- community.general.homebrew:
    name: tmux
  when: ansible_distribution == 'MacOSX'