---
- name: "Package: zsh"
  ansible.builtin.apt:
    name: zsh
  become: true
  when: ansible_facts['os_family'] == "Debian"
- name: "Package: zsh"
  community.general.homebrew:
    name: zsh
  when: ansible_distribution == 'MacOSX'
- name: Get the current user
  ansible.builtin.command: whoami
  register: whoami
  changed_when: false
- name: Get the path to zsh
  ansible.builtin.command: which zsh
  register: zsh
  changed_when: false
- name: Make zsh default shell
  become: true
  ansible.builtin.user:
    name: "{{ whoami.stdout }}"
    shell: "{{ zsh.stdout }}"
