---
- ansible.builtin.apt:
    name: zsh
  become: true
  when: ansible_distribution == "Ubuntu"
- community.general.homebrew:
    name: zsh
  when: ansible_distribution == 'MacOSX'
- ansible.builtin.shell: whoami
  register: whoami
- ansible.builtin.shell: which zsh
  register: zsh
- name: Make zsh default shell
  become: true
  ansible.builtin.user:
    name: "{{ whoami.stdout }}"
    shell: "{{ zsh.stdout }}"
- ansible.builtin.git:
    repo: https://github.com/zplug/zplug.git
    dest: ~/.zplug
- ansible.builtin.shell: "{{ zsh.stdout }} -c 'source ~/.zshrc && zplug install'"