- name: Ensure .dotfiles repo is present # noqa: latest # Ansible Lint wants a version specified
  ansible.builtin.git:
    repo: git@github.com:macguirerintoul/.dotfiles.git
    dest: ~/.dotfiles
- name: Ensure the ~/.ssh directory exists, so ~/.ssh/config can be copied
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: "0700"
- name: Find all files in ~/.dotfiles/home
  ansible.builtin.find:
    paths: ~/.dotfiles/home
    file_type: "file"
    hidden: true
    recurse: false
  register: dotfiles_find
- name: Create links to ~/.dotfiles/home from ~
  ansible.builtin.file:
    src: "{{ item.path }}"
    path: "~/{{ item.path | regex_search('(?<=.dotfiles\/home\/).*') }}"
    state: link
    force: true # force link if file already exists
  with_items: "{{ dotfiles_find.files }}"
- name: Create link to Zsh plugins directory
  ansible.builtin.file:
    src: ~/.dotfiles/home/.zsh_plugins
    path: ~/.zsh_plugins
    state: link
    force: true # force link if file already exists
- name: Create link to Vim configuration directory
  ansible.builtin.file:
    src: ~/.dotfiles/home/.vim
    path: ~/.vim
    state: link
    force: true # force link if file already exists
