---
- ansible.builtin.apt:
    name:
      - nnn
      - most
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"
- ansible.builtin.expect:
    command: sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)"
    responses:
      (?i)different: "o" # Overwrite if plugin is already present
