- name: Add Node.js asdf plugin
  ansible.builtin.command: asdf plugin add nodejs
  register: nodejs_plugin
  changed_when: nodejs_plugin.rc == 0
  failed_when: nodejs_plugin.rc not in [ 0, 2 ] # asdf returns 2 when plugin is already added
- name: Install Node.js
  ansible.builtin.command: asdf install nodejs latest:18
  register: nodejs_installed 
  changed_when: "'already added' in nodejs_installed.stdout" 