- name: Upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Upgrade Homebrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  when: ansible_distribution == 'MacOSX'
