---
- name: Configure sshd
  become: true
  block:
    - name: Change SSH port
      ansible.builtin.lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port 9753"
    - name: Reload ssh
      become: true
      ansible.builtin.service:
        name: ssh
        state: restarted
