---
name: CI
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  macOS:
    name: macOS
    runs-on: macos-12
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install Ansible
        run: brew install ansible
      - name: Install requirements
        run: ansible-galaxy install -r requirements.yml
      - name: Test the playbook
        run: ansible-playbook pb-personal.yml --skip-tags no-ci -vvv -i inventory-ci.ini
  nitecloud:
    name: nitecloud
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install Ansible
        run: ./install-ansible.sh
      - name: Install requirements
        run: ansible-galaxy install -r requirements.yml
      - name: Test the playbook
        run: ansible-playbook pb-nitecloud.yml --skip-tags no-ci -vvv -i inventory-ci.ini
