---
name: CI
'on':
  pull_request:
    branches:    
      - main
  push:
    branches:
      - main
jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install Ansible
        run: brew install ansible
      - name: Uninstall GitHub Actions' built-in browser installs
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app
      - name: Test the playbook.
        run: ansible-playbook macOS.yml